Algoritmo "triangulo"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/3/2017
Var
// Seção de Declarações das variáveis 
base, altura, area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Entre a base do triângulo: ")


Fimalgoritmo